# Generated by Django 3.1 on 2021-03-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210302_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='b_user',
            new_name='b_author',
        ),
    ]
