# Generated by Django 3.1 on 2021-03-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210302_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdetail',
            old_name='urls',
            new_name='urls_links',
        ),
        migrations.AddField(
            model_name='postdetail',
            name='url_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
